### ISSUE TITLE
Basic text commands can just be stored in the DB

### ISSUE THREAD

**Issue by jmariondev** [otter-computer/GaymersBot#125]
We could implement the basic "action" commands (eg hug, slap, etc) to be saved in the database. This would allow us to add, remove, or edit these commands at runtime without code changes and would de-clutter the codebase of a many functionally similar commands.

**Comment by otter-computer** [comment]
It would be simpler to just create a `simpleCommand` that can accept a parameter to tell Disco which type it is and just combine all of them into one. So you can fire something like `simpleCommand('hug', user);` and it'll respond appropriately.

Adding responses into the database is likely overkill, considering we can just add more by editing the file directly using GitHub's online editor if we really want to, but frankly we haven't really changed any of them since before *I* even started work on DiscoBot.
