### ISSUE TITLE
Track game time of games played on server

### ISSUE THREAD

**Issue by brandon-a** [otter-computer/GaymersBot#145]
Track games played on server, and rank from most time played of each game from highest to lowest.

League: 20 days, 13 hours
Overwatch: 13 days, 5 hours

The stats should reset each week and we could think of various ways to track the time.

**Comment by otter-computer** [comment]
Maybe we should think about bringing back the `!playing` command for this sort of thing too.

**Comment by chrislennon** [comment]
was bored, browsing my mails and thought i would throw in my $0.02
This could be implemented like below (though please don't :neckbeard: )

- Using the [presence event](https://discordjs.readthedocs.io/en/8.2.0/docs_client.html#presence) log the start of a game/ come online (with a game)
- Push that (with a reference to the userid) out to whatever DB is used these days.
- On exit status (offline/leave game/different game) look up the corresponding user entry for the start event
- Do a time diff and log (in the DB, seperate table) that against a key of that game name/id appending to the total
- Create a command to read (sort and sanitize) the DB table
- Create a command to purge each week (user initiated) or use a DB function (stored procedure etc) to automatically truncate the table

are you sure you want this? 😈

**Comment by brandon-a** [comment]
That sounds like a good way to do it. I would add that for the last bullet point, maybe we can try to remove data older than a week on a rolling basis, or maybe once per day, that way the hours don't vary wildly every time the week resets.

**Comment by jmariondev** [comment]
That's kind of what I had in mind @chrislennon, though I was thinking in SQL, not this key-value nonsense kids are all crazy about nowadays :neckbeard:...

I reckon that's our go-to but perhaps with rolling trim like @brandon-a suggested, maybe keeping a week of data? I suppose that depends on how much data we can have in Firebase before Google starts demanding money... 😛

**Comment by chrislennon** [comment]
I totally agree on the SQL side too, operations will be much easier if we can rely on more views or stored procedures.
I bounced some ideas around with @ThomasShaped last night (offline... come to think of it I probably should rejoin the server 👼 ).
Given that there may be requirements for this data to be used outside of discord (for example stats on a website). What I was thinking was to host it on RDS (MySQL hosted on AWS) and rather than manage the connections etc in the bot (like was attempted before), instead put API Gateway (also AWS) in front of it (maybe in combination with lambda too).

This would provide a rest API towards the database, in my opinion this would be cleaner to fire a POST call to submit data on events. Also get the benefit of not having to build DB interaction into any front end website, just a single GET call.

On the data retention discussion - there are quite a few considerations on this technical things as well as privacy stuff (the old !playing command showed me more about users than I really wanted to know). But as a start I was thinking of holding all events (online/offline/game-start/game-stop etc) for ~30 days. This will allow us to play with the creation of stats tables while we figure out how/what we want to do with a horde of data 😉

**Comment by jmariondev** [comment]
@chrislennon Are you proposing that the stats tracking system be decoupled from the bot? I'm not sure we need to go that far... Perhaps just have the stats module handle Postgres or MySQL (or w/e we use) for stats only? Personally I'm more used to SQL so I'd use it throughout the bot but if we already have Firebase for the other functions then there's not much reason to switch now.

**Comment by chrislennon** [comment]
@LuaMilkshake The biggest decouple I'm proposing  would be that the bot stats gathering only communicates to the DB over 1/2 HTTP calls (provided by API gateway). I have no intention of touching the firebase magic & other stuff 😉 . 

For the bot side is an event listener and a small http send function and we can go SQL crazy with views and stored procedures, when ready we can just tie an http endpoint to that table/view and call the relevant command !displaystats or whatevers.

I'll try work up a test version this evening.

**Comment by otter-computer** [comment]
@LuaMilkshake Preferably yes, that way we can use/fill those stats from other places like a website etc.

Currently the only thing firebase is used for now is the `!timeout` command so maybe eventually we can transition that over to aws too.

**Comment by otter-computer** [comment]
#174 added logging of game stats every 5 minutes

**Comment by chrislennon** [comment]
okay, I remember doing lots of work on this before but never really being happy with the end result. I think we should do one of the following:

- Rework the cron based approach to the SQS event system now in place.
- Scrap trying to handle it with SQL etc. and implement [something simple](https://github.com/PaddoInWonderland/PaddoCogs/blob/master/games/games.py) on the Red bot we have available - see how it gets used before moving on with further work.
