### ISSUE TITLE
!status command

### ISSUE THREAD

**Issue by otter-computer** [otter-computer/GaymersBot#146]
We should reimplement the `!status` command to get the bot to tell us if it's alive, and what version/deploy it's running.

**Comment by brandon-a** [comment]
I would prefer not to have any commands that link to GitHub

**Comment by jmariondev** [comment]
Perhaps make such a command only work in the bot dev room and require 'Bot Developer' ?

**Comment by otter-computer** [comment]
Doesn't have to link, just has to display the commit slug preferably to see if it has deployed the latest version.

**Comment by jmariondev** [comment]
Is that exposed as an ENV var or something?

**Comment by otter-computer** [comment]
Not currently, no. How we ended up doing it on the last version of the bot was writing a text file at deploy time that wold then get read in at runtime.

Currently I think there might also be issues with that as Heroku uses a separate git to do its deploying -.- (maybe?)

**Comment by chrislennon** [comment]
If I understand correctly the inbound github webhook was added last night which will at least allow privileged users to see when the bot updates (or more accurately a merge has happened).

For getting the current running version its a little more tricky (but all doable). As @ThomasShaped said, I'm fairly sure heroku doesnt run using it's own git implementation when pushed from github, sadly (though still need to confirm) rules out option 1.

1. [Dyno-metadata](https://devcenter.heroku.com/articles/dyno-metadata) addon (has been enabled) should expose ENV vars on the running process, I couldn't see them by running `env` after logging into the app (using the heroku toolbelt) with `heroku run bash --app appname` - it is possible (though unlikely) that they are there but only inside the running dyno.

2. Implement a CI step like we used to have with codeship, have a step in there to write out the version based on the incoming git commit id.

3. Node magic! :sparkles: heroku builds on the concept of buildpacks (currently set to node) and I believe will [respect ](https://devcenter.heroku.com/articles/nodejs-support#customizing-the-build-process) postinstall and heroku-postbuild. The issue here is that there is still no .git directory to read from etc. however ... more magic :sparkles: :sparkles: ... heroku still holds on to releases that we deploy viewable from `heroku releases --app appname`. So a theoretical way would be to have a script (like this[ ruby example](http://stackoverflow.com/a/15108560)) run on post-install or heroku-postbuild to call the heroku api and get the release info and write it into the app.

Option 3 would be interesting to pursue though will be heroku specific so when/if we move platforms we will need to rework that bit of code/workflow.

**Comment by chrislennon** [comment]
Additionally if anyone is taking a look at scripting option 3 the following is the base command that provides the info required. This will need to be written as something specific to node, likely http.request() or similar.

- `heroku auth:token` - will provide the token, to be set as $HEROKU_API_TOKEN.
- $HEROKU_APP_NAME can either be hard coded or set as a environment variable.

`curl -H "Accept: application/vnd.heroku+json; version=3" -H "Authorization: Bearer $HEROKU_API_TOKEN" -n https://api.heroku.com/apps/$HEROKU_APP_NAME/releases`

From a quick test myself it appears the returned json data is ordered first release to last.
