### ISSUE TITLE
Leaderboards

### ISSUE THREAD

**Issue by Reynbow** [otter-computer/GaymersBot#171]
Set up leaderboards like Mee6 does. Then we can remove Mee6.
Have the leaderboards hosted on https://gaymers.gg/ on a "Leaderboards" page with the top 100 users.

**Comment by jmariondev** [comment]
A thought I had about this was also that we could consider rewarding people for their time spent in VC. This is a complaint people have with Mee6's implementation when they spend the majority of their time in VC and don't type much.

**Comment by brandon-a** [comment]
And now we can also add tacos!

**Comment by ghost** [comment]
And potatoes :)

**Comment by chrislennon** [comment]
### Mee6
This is what he currently does for the level/ranks:

>Each time you post a message you get a *random* number of *XP* between 15 and 25.
>To avoid flood, you can only gain xp once per minute.
>In the server, you can type *!rank* to get your rank and your level.

So in essence we will need to come up with a similar ranking/leveling system as that to be able to remove mee6 entirely. 

Or.... 

Keep Mee6 around and copy over the [stats](https://mee6.xyz/levels/123315443208421377) similar to the 🌮 method below.

### Tacos
- Write a lambda function to scrape our [leaderboard page](https://discord.heytaco.chat/leaderboard/123315443208421377) (and the global?), write to json and send to S3 - website can read this, bit hacky but would work.
  - Maybe contact taco dev see if they have an api instead?
  - bot-to-bot communication, i.e. asking tacobot from discobot, may be possible but since `!taco` commands don't work in DM its a bit more tricky.

### Potatoes
- ⛔️

**Comment by chrislennon** [comment]
For reference [this](https://github.com/cookkkie/mee6/blob/master/chat-bot/plugins/levels.py) is the mee6 level formula:
```python
def _get_level_xp(n):
        return 5*(n**2)+50*n+100
```

**Comment by chrislennon** [comment]
This is totally doable but its a bit of an ass to implement and maintain. So going to close this issue with the following comments:
- Have a discussion on the admin repo about its usage:
  - Will the check for messages sent be server wide or limited to specific channel
  - What is the duration to check for - e.g. messages in the last minute
  - What is the range of the ranks - how long should it take a user to reach the top rank - a month? year? etc.
  - What are the typical rewards, roles added? Nickname prepend [Rank] etc
- On the technical implementation side, if this is ever picked up again - some notes:
  -  There is no easy way of getting messages in last time bucket, needs to be a .fetchMessages({limit: 100}) then recuse through time stamps, quite unwieldy.
  - Probably best to limit it to specific channels as bot reading from all channels could give unfair advantages towards rooms like #bot-room etc.
  - There is no way around using a database (or file-store) for this, making use of roles for points is possible but ugly for admins and moderators
  - Applying roles or performing actions on a user may also be unwieldy - to account for points removal - there will need to be a continual look up towards the database and iterate over users applying roles where they do not yet exist, this could be done at the time points are added/removed but I can see that becoming a mess.
