### ISSUE TITLE
Document role order information

### ISSUE THREAD

**Issue by chrislennon** [otter-computer/GaymersBot#247]
Apparently there are silent failures when a role it's trying to manage is above the bots assigned role. Can we provide visual setup docs for the roles page?

**Comment by jmariondev** [comment]
I imagine these are silent because we're ignoring promise rejections? With #187 we can implement a rejection/error handler and get notified of these.

What do you mean by "visual setup docs"?

**Comment by chrislennon** [comment]
Ran into an issue that the roles have to be in a specific order on the server. Bot role must be above the region roles etc. Visual docs would just assist in describing how to set up the server roles.

**Comment by chrislennon** [comment]
@LuaMilkshake do you have an overview of this from the Junkbot server (think that's what its called)? My test server is incomplete with regards to roles and I have no idea what should be on top of what 👼

**Comment by mlarter** [comment]
just my two cents.
the everyone role should definitely be at the bottom since that one is the most restricted.
Then above that, The game labels. and then above that, The Geolocation roles such as North/South America, Europe, etc.
Server Restrictions like +18/-18 and Attachments, etc. should be above that then as we are entering the realm of where these roles start impacting EUX.

I could whip up a server diagram of this in a bubble chart, but the server management tab does a nice listing of this already.
