### ISSUE TITLE
Name Change Log Doesn't Show Account Name

### ISSUE THREAD

**Issue by dustbucket** [otter-computer/GaymersBot#348]
/10characters

**Comment by ghost** [comment]
Besides that, I would actually like to clean up in general the logs in #user-logs and #message-logs since it's still kinda messy, any idea how it would look best?
Right now several logs get redundant with the message and the embed showing almost the same info. It got even more redundant with my latest change in #344 but that was so it wasn't useless on mobile where tags become invalid when a user leaves.

**Comment by otter-computer** [comment]
Fixed in #352
