### ISSUE TITLE
Server specific nicknames cause certain commands to fail

### ISSUE THREAD

**Issue by otter-computer** [otter-computer/GaymersBot#38]
If a user has set a server specific nickname and uses a command that contains `msg.mentions` then DiscoBot is unable to resolve their user ID.

Discord prepends their ID with a `!` but it can be easily detected like so.

```
// Server nickname detection
if(userId.substr(2, 1) === "!") {
  fixedId = userId.slice(3, userId.length - 1);
} else {
  fixedId = userId.slice(2, userId.length - 1);
}
```

**Comment by otter-computer** [comment]
`!joined` is broken from this.

**Comment by chrislennon** [comment]
this may just be a brain fart but this _should_ never happen. I suspect we have broken commands/issues with users because we are not using .mentions enough :stuck_out_tongue_winking_eye: 

According to [msg.mentions](http://discordjs.readthedocs.io/en/latest/docs_message.html#mentions) and [user.mention()](http://discordjs.readthedocs.io/en/latest/docs_user.html#mention) we _should_ be able to rely on discord.js to resolve it for us. I think when we start manually taking the id and messing with it in strings we are messing up the resolving.

**Comment by otter-computer** [comment]
Aye, but those docs were written back in Feb, _well_ before the new server nickname stuff came in. I betcha they haven't been updated to account for that yet.

`resource.match(/<@[0-9]+>/g)` is the code that does it, and I don't think that accounts for `!` after the `@` when they have a server specific nickname.

**Comment by chrislennon** [comment]
Ask in discord.js discord maybe too?

**Comment by chrislennon** [comment]
Version 7.0.1 docs were updated may 8th btw, let's have a look this evening see if we can replicate the issue ;)

**Comment by chrislennon** [comment]
https://github.com/hydrabolt/discord.js/issues?q=is%3Aissue+mention+is%3Aclosed

waiting for the release of the in development code or premerging it should fix this issue.
