### ISSUE TITLE
Discobot restricts new members from posting links/files

### ISSUE THREAD

**Issue by otter-computer** [otter-computer/GaymersBot#54]
> Why have we still not made it so that DiscoBot or something adds the link/file restriction for the first three or so days of people joining. Maybe even a week of joining. I can not think of a single downside at all.

-reynbow

**Comment by otter-computer** [comment]
> I may be able to do it by using the joined date and time difference, no need for database and cron that way I guess

-leapyearboy

**Comment by chrislennon** [comment]
Why? Cause you opened the issue less than a minute ago? 😂
What may be an 'interesting' approach is use the users presence change and if not hasRole check the delta time since user.joined and add if appropriate.

Yes we are checking roles every status change but it's better than saving a log/table of allowed users etc

**Comment by otter-computer** [comment]
lol srry, that was just a copypaste of reynbow and your comments from the discobot chat so we didn't lose it 😂
